name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
    - name: Gradle cache
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: ./gradlew test
    - name: Unit tests results
      uses: actions/upload-artifact@v4
      with:
        name: unit-tests-results
        path: build/reports/tests/test
